<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
=======
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import Footer from "./_components/footer"

const inter = Inter({ subsets: ["latin"] })
>>>>>>> f19835fafdb021309650a4e0f90158cff4a121d9

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
<<<<<<< HEAD
};
=======
}
>>>>>>> f19835fafdb021309650a4e0f90158cff4a121d9

export default function RootLayout({
  children,
}: Readonly<{
<<<<<<< HEAD
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>{children}</body>
    </html>
  );
=======
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  )
>>>>>>> f19835fafdb021309650a4e0f90158cff4a121d9
}
